name = "nuxt-opengraph"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "307ebd51f6c21a90c3873587c11a2913"
# route = "<mainly useful when you want to setup custom domains (optional too)>"

[site]
bucket = ".output/public"
