name = "nuxt-opengraph"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "b3f9fdfd827152316d080a5ddee59915"
# route = "<mainly useful when you want to setup custom domains (optional too)>"

[site]
bucket = ".output/public"
