name = "capture"
account_id = "030ea74508b6ec03b9b1a6ff69a591a8"

main = "src/index.ts"
compatibility_date = "2023-10-25"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "MYBROWSER" }
# kv_namespaces = [
#   { binding = "BROWSER_KV_DEMO", id = "22cf855786094a88a6906f8edac425cd", preview_id = "e1f8b68b68d24381b57071445f96e623" }
# ]

