name = "prerender-beta"
main = "src/worker.ts"
compatibility_date = "2023-05-18"

routes = [
	"*.kodadot.xyz/stmn/drops/*",
	"*.kodadot.xyz/stt/drops/*",
]

[env.beta]
name = "prerender-beta"

[env.production]
name = "prerender"
routes = [
	"kodadot.xyz/stmn/drops/*",
	"kodadot.xyz/stt/drops/*",
]
