name = "durable-jpeg"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "b3f9fdfd827152316d080a5ddee59915"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-11"

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "JPEG", class_name = "DurableJpeg"}]

[[migrations]]
tag = "v0" # Should be unique for each entry
new_classes = ["DurableJpeg"]
