name = "ssr-opengraph-beta"
compatibility_date = "2023-06-21"
main = "src/index.tsx"
routes = [
  "*.kodadot.xyz/*/gallery/*",
  "*.kodadot.xyz/*/detail/*",
  "*.kodadot.xyz/*/collection/*",
  "*.kodadot.xyz/*/u/*",
]

[env.beta]
name = "ssr-opengraph-beta"

[env.production]
name = "ssr-opengraph"
routes = [
  "kodadot.xyz/*/gallery/*",
  "kodadot.xyz/*/detail/*",
  "kodadot.xyz/*/collection/*",
  "kodadot.xyz/*/u/*",
]
