name: Deploy ssr-opengraph

on:
  push:
    branches:
      - main
    paths:
      - 'ssr-opengraph/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ssr-opengraph
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm install
          workingDirectory: 'ssr-opengraph'