account_id = "b3f9fdfd827152316d080a5ddee59915"
compatibility_date = "2023-01-03"
main = "src/index.ts"
name = "image-beta"
usage_model = "bundled"

[vars]
DEDICATED_GATEWAY = 'https://kodadot-ultra.myfilebase.com'
DEDICATED_BACKUP_GATEWAY = 'https://kodadot1.infura-ipfs.io'
CLOUDFLARE_GATEWAY = 'https://cloudflare-ipfs.com'
CF_IMAGE_ACCOUNT = 'b3f9fdfd827152316d080a5ddee59915'
CF_IMAGE_ID = 'jk5b6spi_m_-9qC4VTnjpg'

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'alpha-stockpile'
preview_bucket_name = 'alpha-stockpile'

# 'vars' and 'r2_buckets' are non-inheritable keys
# https://developers.cloudflare.com/workers/wrangler/configuration/#non-inheritable-keys

# beta environment
[env.beta]
name = 'image-beta'

[env.beta.vars]
CF_IMAGE_ACCOUNT = 'b3f9fdfd827152316d080a5ddee59915'
CF_IMAGE_ID = 'jk5b6spi_m_-9qC4VTnjpg'
CLOUDFLARE_GATEWAY = 'https://cloudflare-ipfs.com'
DEDICATED_BACKUP_GATEWAY = 'https://kodadot1.infura-ipfs.io'
DEDICATED_GATEWAY = 'https://kodadot-ultra.myfilebase.com'

[[env.beta.r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'stockpile'
preview_bucket_name = 'alpha-stockpile'

# production environment
[env.production]
name = 'image'

[env.production.vars]
CF_IMAGE_ACCOUNT = 'b3f9fdfd827152316d080a5ddee59915'
CF_IMAGE_ID = 'jk5b6spi_m_-9qC4VTnjpg'
CLOUDFLARE_GATEWAY = 'https://cloudflare-ipfs.com'
DEDICATED_BACKUP_GATEWAY = 'https://kodadot1.infura-ipfs.io'
DEDICATED_GATEWAY = 'https://kodadot-ultra.myfilebase.com'

[[env.production.r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'stockpile'
preview_bucket_name = 'alpha-stockpile'
